//
//  SpendingCategory.swift
//
//
//  Created by TM.Dev on 15/07/2024.
//

import Foundation

public enum SpendingCategory: String, Codable {
    case bike = "BIKE"
    case billsAndServices = "BILLS_AND_SERVICES"
    case bucketList = "BUCKET_LIST"
    case car = "CAR"
    case cash = "CASH"
    case celebration = "CELEBRATION"
    case charity = "CHARITY"
    case children = "CHILDREN"
    case clothes = "CLOTHES"
    case coffee = "COFFEE"
    case debtRepayment = "DEBT_REPAYMENT"
    case diy = "DIY"
    case drinks = "DRINKS"
    case eatingOut = "EATING_OUT"
    case education = "EDUCATION"
    case emergency = "EMERGENCY"
    case entertainment = "ENTERTAINMENT"
    case essentialSpend = "ESSENTIAL_SPEND"
    case expenses = "EXPENSES"
    case family = "FAMILY"
    case fitness = "FITNESS"
    case fuel = "FUEL"
    case gambling = "GAMBLING"
    case gaming = "GAMING"
    case garden = "GARDEN"
    case general = "GENERAL"
    case gifts = "GIFTS"
    case groceries = "GROCERIES"
    case hobby = "HOBBY"
    case holidays = "HOLIDAYS"
    case home = "HOME"
    case impulseBuy = "IMPULSE_BUY"
    case income = "INCOME"
    case insurance = "INSURANCE"
    case investments = "INVESTMENTS"
    case lifestyle = "LIFESTYLE"
    case maintenanceAndRepairs = "MAINTENANCE_AND_REPAIRS"
    case medical = "MEDICAL"
    case mortgage = "MORTGAGE"
    case nonEssentialSpend = "NON_ESSENTIAL_SPEND"
    case payments = "PAYMENTS"
    case personalCare = "PERSONAL_CARE"
    case personalTransfers = "PERSONAL_TRANSFERS"
    case pets = "PETS"
    case projects = "PROJECTS"
    case relationships = "RELATIONSHIPS"
    case rent = "RENT"
    case saving = "SAVING"
    case shopping = "SHOPPING"
    case subscriptions = "SUBSCRIPTIONS"
    case takeaway = "TAKEAWAY"
    case taxi = "TAXI"
    case transport = "TRANSPORT"
    case treats = "TREATS"
    case wedding = "WEDDING"
    case wellbeing = "WELLBEING"
    case none = "NONE"
    case revenue = "REVENUE"
    case otherIncome = "OTHER_INCOME"
    case clientRefunds = "CLIENT_REFUNDS"
    case inventory = "INVENTORY"
    case staff = "STAFF"
    case travel = "TRAVEL"
    case workplace = "WORKPLACE"
    case repairsAndMaintenance = "REPAIRS_AND_MAINTENANCE"
    case admin = "ADMIN"
    case marketing = "MARKETING"
    case businessEntertainment = "BUSINESS_ENTERTAINMENT"
    case interestPayments = "INTEREST_PAYMENTS"
    case bankCharges = "BANK_CHARGES"
    case other = "OTHER"
    case foodAndDrink = "FOOD_AND_DRINK"
    case equipment = "EQUIPMENT"
    case professionalServices = "PROFESSIONAL_SERVICES"
    case phoneAndInternet = "PHONE_AND_INTERNET"
    case vehicles = "VEHICLES"
    case directorsWages = "DIRECTORS_WAGES"
    case vat = "VAT"
    case corporationTax = "CORPORATION_TAX"
    case selfAssessmentTax = "SELF_ASSESSMENT_TAX"
    case investmentCapital = "INVESTMENT_CAPITAL"
    case transfers = "TRANSFERS"
    case loanPrincipal = "LOAN_PRINCIPAL"
    case personal = "PERSONAL"
    case dividends = "DIVIDENDS"
}
